---
#
# Install Browbeat Monitoring on OpenStack
#

- name: Install Browbeat Monitoring on the Undercloud
  hosts: undercloud
  gather_facts: false
  remote_user: stack
  vars_files:
    - vars/browbeat.yml
  pre_tasks:
    - name: Ensure remote log directory exists
      file:
        path: /home/stack/alderaan-deploy/log/browbeat
        state: directory
        owner: stack
        group: stack
  roles:
    - name: update-motd
      vars:
        update_motd: "Installing Browbeat"
    - install-browbeat
    - name: update-motd
      vars:
        update_motd: "Browbeat Installed"
