---
- name: Install Browbeat on the OpenStack server
  hosts: openstack-server
  vars:
    browbeat_ansible_dir: "{{ ansible_user_dir }}/browbeat/ansible"
    graphite_host: "{{ lookup('env', 'GRAPHITE') }}"
    graphite_prefix: "{{ lookup('env', 'GRAPHITE_PREFIX') }}"
    configuration:
      - { find: "graphite_host:.*", replace: "graphite_host: {{ graphite_host }}" }
      - { find: "graphite_prefix:.*", replace: "graphite_prefix: {{ graphite_prefix }}"}

  tasks:
    # Delete any earlier attempts.
    - name: Deleting the browbeat directory
      file:
        path: "{{ ansible_user_dir }}/browbeat"
        state: absent

    # Clone the browbeat repository.
    - name: Cloning the Browbeat repository
      git:
        repo: 'https://github.com/openstack/browbeat.git'
        dest: "{{ ansible_user_dir }}/browbeat"

    # Generate the list of hosts.
    - name: Generating the hosts list
      shell: "./generate_tripleo_hostfile.sh -t localhost 2>&1 > tripleo_hostfile.log"
      args:
        chdir: "{{ browbeat_ansible_dir }}"
        executable: /bin/bash

    # Replace the specific lines in the all.yml configuration file.
    - name: Replacing the lines in the install configuration file
      lineinfile:
        path: "{{ browbeat_ansible_dir }}/install/group_vars/all.yml"
        regexp: "{{ item['find'] }}"
        line: "{{ item['replace'] }}"
      with_items: "{{ configuration }}"

    # Run the collectd installer.
    - name: Running the Ansible playbook to install collectd
      shell: "ansible-playbook -i hosts install/collectd-openstack.yml 2>&1 > collectd_install.log"
      args:
        chdir: "{{ browbeat_ansible_dir }}"
        executable: /bin/bash
