---
#
# Rebuilding the Undercloud tasks
#

- name: Set Machine to rebuild
  delegate_to: localhost
  uri:
    body: "{\"host\": {\"build\": \"1\"}}"
    body_format: json
    force_basic_auth: true
    method: PUT
    password: "{{ticket_number}}"
    url: "{{foreman_url}}/api/hosts/{{undercloud_hostname}}"
    user: "{{cloud_title}}"
    validate_certs: false
  when: rebuild_undercloud | bool

- name: Reboot undercloud
  shell: "sleep 5; reboot now"
  async: 1
  poll: 0
  ignore_errors: true
  when: rebuild_undercloud | bool

# Stop gap to prevent a machine that is slow to reboot from passing
- name: Wait for Machine Rebuilding
  local_action:
    module: wait_for
    host: "{{undercloud_hostname}}"
    port: 22
    delay: 2
    timeout: 300
    state: stopped
  register: wait_for_data
  when: rebuild_undercloud | bool

- name: Wait for Machine Rebuild to complete
  local_action:
    module: wait_for
    host: "{{inventory_hostname}}"
    port: 22
    delay: 600
    timeout: 2000
  when: rebuild_undercloud | bool

# Depending on hardware rebuild, we may not have the ssh key exchanged
- name: Setup root authorized key
  authorized_key:
    user: root
    key: "{{ lookup('file', lookup('env','PUBLIC_KEY')| default('~/.ssh/id_rsa.pub', true)) }}"

# Due to Ansible 2.8 synchronize module does not seem to work if ansible_ssh_pass is used
# Once key is exchanged (above task) we no longer need the ansible_ssh_pass variable
# See https://github.com/ansible/ansible/issues/56629
- name: Remove any password set via ansible_ssh_pass
  set_fact:
    ansible_ssh_pass: ""
