---
# tasks file for rebuild-undercloud

- name: Template rebuild script
  template:
    src: toggle-rebuild.sh.j2
    dest: /tmp/toggle-rebuild.sh
  become: true

- name: Run rebuild script
  shell: "bash /tmp/toggle-rebuild.sh"

- name: Reboot undercloud
  shell: "sleep 5; reboot now"
  async: 1
  poll: 0
  ignore_errors: true
  
- name: Wait for Machine Ready
  local_action:
    module: wait_for
    host: "{{inventory_hostname}}"
    port: 22
    delay: 600
    timeout: 2000
