parameter_defaults:
  ControllerSchedulerHints:
    'capabilities:node': 'controller-%index%'
  P1029ComputeSchedulerHints:
    'capabilities:node': '1029pcompute-%index%'
  CephStorageSchedulerHints:
    'capabilities:node': 'cephstorage-%index%'
