---
# tasks file for overcloud-deploy

- name: Install ostag
  pip:
    state: latest
    virtualenv: /home/stack/ostag-venv
    name: "{{item}}"
  with_items:
    - pip
    - git+https://github.com/redhat-performance/ostag#egg=ostag

- name: Fix os-client-config version for ostag
  pip:
    name: os-client-config
    version: 1.29.0
    virtualenv: "{{home_dir}}/ostag-venv"

- name: Template the Pinning script
  template:
    src: pin-nodes.sh.j2
    dest: /home/stack/pin-nodes.sh

- name: Pin the nodes
  shell: source /home/stack/stackrc; bash /home/stack/pin-nodes.sh

- name: Template deploy script
  template:
    src: overcloud-deploy.sh.j2
    dest: /home/stack/overcloud-deploy.sh

- name: Deploy the overcloud
  shell: bash /home/stack/overcloud-deploy.sh
