---
# tasks file for overcloud-prepare-templates

- name: Copy Alderaan THT Files into templates directory
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: stack
    group: stack
    mode: "{{item.mode | default('0644')}}"
  with_items:
    - src: files/1029p-storage-environment.yaml
      dest: /home/stack/templates/1029p-storage-environment.yaml
    - src: files/1029u-storage-environment.yaml
      dest: /home/stack/templates/1029u-storage-environment.yaml
    - src: files/args.yaml
      dest: /home/stack/templates/environments/args.yaml
    - src: files/compute-params.yaml
      dest: /home/stack/templates/environments/compute-params.yaml
    - src: files/controller-params.yaml
      dest: /home/stack/templates/environments/controller-params.yaml
    - src: files/disable-notifications.yaml
      dest: /home/stack/templates/disable-notifications.yaml
    - src: files/firstboot-env.yaml
      dest: /home/stack/templates/environments/firstboot-env.yaml
    - src: files/first-boot.yaml
      dest: /home/stack/templates/firstboot/first-boot.yaml
    - src: files/roles_data-notelem.yaml
      dest: /home/stack/templates/roles_data-notelem.yaml
    - src: files/scheduler-hints.yaml
      dest: /home/stack/templates/scheduler-hints.yaml

    # Private External Nic-config "templates"
    - src: files/nic-configs/private/1029p-cephstorage.yaml
      dest: /home/stack/templates/nic-configs/0/1029p-cephstorage.yaml
    - src: files/nic-configs/private/1029p-compute.yaml
      dest: /home/stack/templates/nic-configs/0/1029p-compute.yaml
    - src: files/nic-configs/private/1029p-controller.yaml
      dest: /home/stack/templates/nic-configs/0/1029p-controller.yaml
    - src: files/nic-configs/private/1029u-cephstorage.yaml
      dest: /home/stack/templates/nic-configs/0/1029u-cephstorage.yaml
    # Public External Nic-config "templates"
    - src: files/nic-configs/public/1029p-cephstorage.yaml
      dest: /home/stack/templates/nic-configs/1/1029p-cephstorage.yaml
    - src: files/nic-configs/public/1029p-compute.yaml
      dest: /home/stack/templates/nic-configs/1/1029p-compute.yaml
    - src: files/nic-configs/public/1029p-controller.yaml
      dest: /home/stack/templates/nic-configs/1/1029p-controller.yaml
    - src: files/nic-configs/public/1029u-cephstorage.yaml
      dest: /home/stack/templates/nic-configs/1/1029u-cephstorage.yaml

- name: Copy Alderaan THT Templates into templates directory
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: stack
    group: stack
  with_items:
    - src: templates/deploy.yaml.j2
      dest: /home/stack/templates/deploy.yaml
    - src: templates/network-environment.yaml.j2
      dest: /home/stack/templates/network-environment.yaml

- name: Place version metadata json file in /etc
  become: true
  template:
    src: templates/version.json.j2
    dest: /etc/version.json
    owner: stack
    group: stack
