---
#
# Tasks for post deployment
#

- name: Create the public network and subnet
  shell: |
    . /home/stack/overcloudrc
    /home/stack/alderaan-deploy/create_public_cluster_network.sh

- name: Run post deploy workarounds
  shell: |
    . /home/stack/stackrc
    /home/stack/alderaan-deploy/post_deploy_workarounds.sh {{log_dir}}
