---
#
# Playbook for deploying Tripleo OpenStack for OpenShift in ScaleLab
#

- name: Run initial setup tasks
  hosts: undercloud
  gather_facts: true
  remote_user: root
  roles:
    - rebuild-undercloud
    - undercloud-prepare-host

- name: Run OSP install
  hosts: undercloud
  gather_facts: false
  remote_user: stack
  roles:
    - undercloud-install
    - overcloud-prepare-templates
    - overcloud-deploy
    - scalelab-network
    - scalelab-inventory
