---

- name: Ensure gather_facts has been run against localhost
  setup:
  delegate_to: localhost
  delegate_facts: True
  when: hostvars['localhost'].ansible_user_dir is not defined

- name: Ensure gather_facts has been run against undercloud
  setup:

- include_tasks: inventory.yml

